force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <displayFormat>PVR-{0000}</displayFormat>
        <label>Phone Validation Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Phone Validation Results</relationshipLabel>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ValidationCalloutTest.cls
@isTest
private class ValidationCalloutTest {
    @isTest static void personCreationTest() {
        Person__c p=TestDataFactory.createPeople('test', 1)[0];
        p.Phone__c='+381604009911';

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('PhoneValidationSuccess');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);

        Test.startTest();
        insert p;
        Test.stopTest();
        //problem if another test creates more phone validation results??????
        System.assert([select Name from Phone_Validation_Result__c where Person__c=:p.Id limit 1]!=null, 'The Phone Validation Result was not created');

    }

    @isTest static void personErrorUpdateTest() {
        Person__c p=TestDataFactory.createPeople('test', 1)[0];
        p.Phone__c='0604009911';
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('PhoneValidationSuccess');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        insert p;
        mock.setStaticResource('PhoneValidationError');
        p.Phone__c='';

        Test.startTest();
        update p;
        Test.stopTest();

        System.assert([select Name from Phone_Validation_Result__c where Person__c=:p.Id limit 1]!=null, 'The Phone Validation Result was not created');

    }
}