force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <displayFormat>PVR-{0000}</displayFormat>
        <label>Phone Validation Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/CountryPrefix__c.field-meta.xml
<CustomField>
    <fullName>CountryPrefix__c</fullName>
    <label>CountryPrefix</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/ErrorId__c.field-meta.xml
<CustomField>
    <fullName>ErrorId__c</fullName>
    <label>ErrorId</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/ErrorResolution__c.field-meta.xml
<CustomField>
    <fullName>ErrorResolution__c</fullName>
    <label>ErrorResolution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/IsValid__c.field-meta.xml
<CustomField>
    <fullName>IsValid__c</fullName>
    <label>IsValid</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NationalFormat__c.field-meta.xml
<CustomField>
    <fullName>NationalFormat__c</fullName>
    <label>NationalFormat</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCode__c.field-meta.xml
<CustomField>
    <fullName>NetworkCode__c</fullName>
    <label>NetworkCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkCountry__c.field-meta.xml
<CustomField>
    <fullName>NetworkCountry__c</fullName>
    <label>NetworkCountry</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NetworkName__c.field-meta.xml
<CustomField>
    <fullName>NetworkName__c</fullName>
    <label>NetworkName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/NumberType__c.field-meta.xml
<CustomField>
    <fullName>NumberType__c</fullName>
    <label>NumberType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Phone Validation Results</relationshipLabel>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>PhoneNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/RequestProcessed__c.field-meta.xml
<CustomField>
    <fullName>RequestProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RequestProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationAPISettings__mdt/ValidationAPISettings__mdt.object-meta.xml
<CustomObject>
    <label>ValidationAPISettings</label>
    <pluralLabel>ValidationAPISettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ValidationAPISettings__mdt/fields/KeyValue__c.field-meta.xml
<CustomField>
    <fullName>KeyValue__c</fullName>
    <label>KeyValue</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhoneValidCallout.cls
public with sharing class PhoneValidCallout {
    public PhoneValidCallout() {
        @future(callout=true)
        public static void makeCallout(ID personId, String newPhone, String fieldName) {
            HttpRequest request = new HttpRequest();
            String endpoint = ValidationAPISettings__mdt.getInstance('default').URL__c+'?Key='+ValidationAPISettings__mdt.getInstance('default').KeyValue__c+'&Phone='+newPhone;
            request.setEndPoint(endpoint);
            request.setMethod('GET');
            HttpResponse res = new HTTP().send(request);
            Phone_Validation_Result__c validRes=new Phone_Validation_Result__c();
            validRes.ValidatedFieldValue=newPhone;
            validRes.ValidatedFieldName=fieldName; //Is this dumb????????
            validRes.Person__c=personId;
            if (res.getStatusCode()==200){
                Map<string,object> m = (Map<string,object>)JSON.deserializeUntyped(res.getbody());
                validRes.PhoneNumber__c=(String)m.get('PhoneNumber');
                validRes.RequestProcessed__c=(Boolean)m.get('RequestProcessed');
                validRes.IsValid__c=(String)m.get('IsValid');
                validRes.NetworkCode__c=(String)m.get('NetworkCode');
                validRes.NetworkName__c=(String)m.get('NetworkName');
                validRes.NetworkCountry__c=(String)m.get('NetworkCountry');
                validRes.NationalFormat__c=(String)m.get('NationalFormat');
                validRes.CountryPrefix__c=(Integer)m.get('CountryPrefix');
                validRes.NumberType__c=(String)m.get('NumberType');
            }
            else{
                validRes.ErrorId__c=(Integer)m.get('Id');
                validRes.Error__c=(String)m.get('Error');
                validRes.ErrorCause__c=(String)m.get('Cause');
                validRes.ErrorResolution__c=(String)m.get('Resolution');
            }
            insert validRes;


        }

    }
}